### PR TITLE
mac80211: injection patch

### PR DESCRIPTION
**Pull request by ghpranav**

### CODE REVIEW

**Comment by fgl27** [comment]
way?

**Comment by ghpranav** [comment]
This patch adds monitor mode support. Patch taken from here: 
http://patches.aircrack-ng.org/mac80211.compat08082009.wl_frag+ack_v1.patch

**Comment by fgl27** [comment]
what is the need to all users for it?
have you try it works?
way can you just make and run yours on kernel?
for mod and hack like this, this is a security breech this branch is not for that is for the against.

this is a stable secure branch.

**Comment by ghpranav** [comment]
I don't have tools to compile kernel. So, can u plz give me an experimental build of this kernel with my commit merged? (No need of merging it in stable branch). By this, I will be able to complete my Kali NetHunter OS port for our device. Thanks in advance.

**Comment by ghpranav** [comment]
And moreover, monitor mode isn't a security breach, instead it's an added feature for the kernel, which helps users to use their mobiles for PenTesting. You can Google about it, many people even use wifi adapter for monitor mode...

**Comment by fgl27** [comment]
but you are using to hack? don't you?

and that is a weakening of security as the hack can be reverted or at least used to do no good, that is way it is never implemented on the first place, not a expert on this but there is reasons this function is not wide spread on android.

send you a kernel when I have time to make one...

**Comment by ghpranav** [comment]
Kk, thx a lot

**Comment by fgl27** [comment]
https://www.androidfilehost.com/?fid=745425885120757715

:+1:

**Comment by ghpranav** [comment]
Thx a lot :) 👍

**Comment by ghpranav** [comment]
Bro, I think u have forgotten to include my commit in that build :/

**Comment by fgl27** [comment]
I included and reverted because I don't wanna, I build and share that before revert if doesn't work try to find out way and let me know.

**Pull request closed without merging**
